version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: sensor_timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sensorprocessing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
